steps:
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
      - 'stale'
    owner: 'Bruce6X'
    repository: 'jenkins-library'
    releaseBodyHeader: ''
  githubCreatePullRequest:
    base: master
    owner: 'Bruce6X'
    repository: 'jenkins-library'
    labels:
      - 'REVIEW'
      - 'go-piper'
    assignees:
      - 'marcusholl'
      - 'daniel-kurzynski'
      - 'fwilhe'
      - 'CCFenner'
      - 'OliverNocon'
      - 'nevskrem'
